"""empty message

Revision ID: 26e1f441f0b8
Revises: b3adbeba0320
Create Date: 2016-10-10 15:54:08.864706

"""

# revision identifiers, used by Alembic.
revision = '26e1f441f0b8'
down_revision = 'b3adbeba0320'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
